{
 "title": "Alert Manager",
 "description": "The dashborad using Prometheus AlertManager datasource 0.0.6 version.",
 "tags": [ "0.0.1" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All alerts",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"JobInstanceDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "High Memory Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"MemoryFree10%\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "High CPU Node Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"HostCPUUtilisation\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Load Average 15 Min",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"LoadAverage15m\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(up)", "labelSelector": "*", "target": "Query", "type": "timeserie" }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "labelSelector": "*", "legendFormat": "{{ summary }}", "target": "Query", "type": "table" },
    { "labelSelector": "*", "legendFormat": "{{ instance }}", "target": "Query", "type": "table" }
   ]
  }
 ]
}