# my global config
global:
  scrape_interval:     120s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 120s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "rules.yml"
  # - "second_rules.yml"

# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

#########################################################################
##########################################################################
###########################<< AGGREGATION 1 >>############################
##########################################################################
##########################################################################
##########################################################################

  - job_name: 'AGG1-name'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - name
      - name: tag:Environment
        values:
          - FREE-Production
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.


  - job_name: 'AGG1-nameRetry'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - nameRetry
      - name: tag:Environment
        values:
          - FREE-Production
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-FreeProd-namenamename'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - FreeProd-namenamename
      - name: tag:Environment
        values:
          - FREE-Production
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-FreeProd-SearchProfilename'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - FreeProd-SearchProfilename
      - name: tag:Environment
        values:
          - FREE-Production
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-FreeProd-SearchProfilenameRetry-1'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - FreeProd-SearchProfilenameRetry-1
      - name: tag:Environment
        values:
          - FREE-Production
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-prod-paid-name-daily-review-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-daily-review-agg
      - name: tag:Environment
        values:
          - prod
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-prod-paid-name-daily-review-agg-retry'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-daily-review-agg-retry
      - name: tag:Environment
        values:
          - prod
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-prod-paid-name-competitor-review-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-competitor-review-agg
      - name: tag:Environment
        values:
          - prod
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-prod-paid-name-rename-review-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-rename-review-agg
      - name: tag:Environment
        values:
          - prod
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-prod-paid-name-replies-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-replies-agg
      - name: tag:Environment
        values:
          - prod
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-prod-paid-name-asg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 120s
      port: 9100
      filters:
      - name: tag:Name
        values:
          - prod-paid-name-asg
      - name: tag:Environment
        values:
          - prod
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG1-free-paid-name-asg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 120s
      port: 9100
      filters:
      - name: tag:Name
        values:
          - free-prod-name-asg
      - name: tag:Environment
        values:
          - freeprod
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

#########################################################################
#########################################################################
##########################<< AGGREGATION 2 >>############################
#########################################################################
#########################################################################
#########################################################################

  - job_name: 'AGG2-name'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - name
      - name: tag:Environment
        values:
          - FREE-Production
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.


  - job_name: 'AGG2-nameRetry'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - nameRetry
      - name: tag:Environment
        values:
          - FREE-Production
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-FreeProd-namenamename'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - FreeProd-namenamename
      - name: tag:Environment
        values:
          - FREE-Production
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-FreeProd-SearchProfilename'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - FreeProd-SearchProfilename
      - name: tag:Environment
        values:
          - FREE-Production
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-FreeProd-SearchProfilenameRetry-1'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - FreeProd-SearchProfilenameRetry-1
      - name: tag:Environment
        values:
          - FREE-Production
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-prod-paid-name-daily-review-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-daily-review-agg
      - name: tag:Environment
        values:
          - prod
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-prod-paid-name-daily-review-agg-retry'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-daily-review-agg-retry
      - name: tag:Environment
        values:
          - prod
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-prod-paid-name-competitor-review-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-competitor-review-agg
      - name: tag:Environment
        values:
          - prod
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-prod-paid-name-rename-review-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-rename-review-agg
      - name: tag:Environment
        values:
          - prod
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-prod-paid-name-replies-agg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 300s
      port: 9100
      filters:
      - name: tag:Team
        values:
          - name
      - name: tag:Name
        values:
          - prod-paid-name-replies-agg
      - name: tag:Environment
        values:
          - prod
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-prod-paid-name-asg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 120s
      port: 9100
      filters:
      - name: tag:Name
        values:
          - prod-paid-name-asg
      - name: tag:Environment
        values:
          - prod
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too.

  - job_name: 'AGG2-free-paid-name-asg'
    ec2_sd_configs:
    - region: us-east-1
      refresh_interval: 120s
      port: 9100
      filters:
      - name: tag:Name
        values:
          - free-prod-name-asg
      - name: tag:Environment
        values:
          - freeprod
      role_arn: arn:aws:iam::939261055124:role/sd-prometheus-server-role
    relabel_configs:
    - source_labels: [__meta_ec2_instance_state]
      regex: running
      action: keep
    - source_labels: [__meta_ec2_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'   # Have to specify a port too

