groups:
  - name: recording_rules
    interval: 15s
    rules:
      - record: instance:node_cpu_utilization_percent:rate5m
        expr: 100 * (1 - avg by(instance)(irate(node_cpu{mode='idle'}[5m])))

      - record: node_exporter:node_filesystem_free:fs_used_percents
        expr: 100 - 100 * ( node_filesystem_free{mountpoint="/"} / node_filesystem_size{mountpoint="/"} )

      - record: node_exporter:node_memory_free:memory_used_percents
        expr: 100 - 100 * (node_memory_MemFree / node_memory_MemTotal)

      - record: alerts_fired:24h
        expr:   sort_desc(sum(sum_over_time(ALERTS{alertstate=`firing`}[24h])) by (alertname))

  - name: alerting_rules
    rules:
      - alert: HostCPUUtilisation
        expr: 100 - (avg by(instance) (irate(node_cpu{mode="idle"}[5m])) * 100) > 70
        for: 10m
        labels:
          severity: warning
        annotations:
          description: 'High CPU utilisation detected for instance {{ $labels.instance_id}} tagged as: {{ $labels.instance_name_tag }}, the utilisation is currently:{{ $value }}%'
          summary: CPU Utilisation Alert

      - alert: LoadAverage15m
        expr: node_load15 >= 5.00
        labels:
          severity: major
        annotations:
          summary: "Instance {{ $labels.instance }} - high load average"
          description: "{{ $labels.instance  }} (measured by {{ $labels.job }}) has high load average ({{ $value }}) over 15 minutes."

      - alert: JobInstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} - instance is down"
          description: "Instance {{ $labels.instance }} instance {{ $labels.instance }} is down."

      - alert: Memory_Usage_Above_90_Percent
        expr: (((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes) / (node_memory_MemTotal_bytes) * 100)) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} hight memory usage"
          description: "{{ $labels.instance }} has more than 90% of its memory used."

      - alert: DiskSpace10%Free
        expr: node_filesystem_avail / node_filesystem_size * 100 <= 10
        labels:
          severity: moderate
        annotations:
          summary: "Instance {{ $labels.instance }} is low on disk space"
          description: "{{ $labels.instance }} has only {{ $value }}% free."

      - alert: DiskWillFillIn4Hours
        expr: predict_linear(node_filesystem_free[1h], 4 * 3600) < 0
        labels:
          severity: warning
        annotations:
         summary: "Instance {{ $labels.instance }} disk space will fill in 4 hours, please check logs"
         description: "{{ $labels.instance }} has only {{ $value }}% free."
