groups:
- name: alert.rules
  rules:
  - alert: EndpointDown
    expr: probe_success == 0
    for: 10s
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"

##  SSLCertExpiring Rule
  - alert: SSLCertExpiringSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
    for: 10m
    labels:
      severity: "warning"
    annotations:
      summary: 'SSL Expire Alert'
      description: "SSL certificate for the {{ $labels.instance }} will expire soon!"
