{
 "title": "Aerospike Cluster Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(as_stats_cient_connections, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(as_ns_current_time{instance='$host'}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_stats_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "singlestat",
   "description": "Number of namespaces",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "as_ns_count{instance='$host'}" }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_stats_cluster_size{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "RAM Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_stats_system_free_mem_pct{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_stats_cient_connections{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_stats_objects{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_ns_memory_used_bytes{namespace='$namespace', instance='$host'}"
    }
   ]
  },
  {
   "title": "Device used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_ns_device_used_bytes{namespace='$namespace', instance='$host'}"
    }
   ]
  },
  {
   "title": "Expired",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_ns_expired_objects{namespace='$namespace', instance='$host'}"
    }
   ]
  },
  {
   "title": "Tombstones",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_stats_tombstones{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "High Watermark",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "as_ns_high_water_memory_pct{namespace='$namespace', instance='$host'}",
     "legendFormat": "memory"
    },
    {
     "expr": "as_ns_high_water_disk_pct{namespace='$namespace', instance='$host'}",
     "legendFormat": "disk"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "as_ns_memory_size{namespace='$namespace', instance='$host'}",
     "legendFormat": "total"
    },
    {
     "expr": "as_ns_memory_used_bytes{namespace='$namespace', instance='$host'}",
     "legendFormat": "used"
    },
    {
     "expr": "as_ns_memory_used_index_bytes{namespace='$namespace', instance='$host'}",
     "legendFormat": "index"
    },
    {
     "expr": "as_ns_memory_used_sindex_bytes{namespace='$namespace', instance='$host'}",
     "legendFormat": "sindex"
    }
   ]
  },
  {
   "title": "Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "as_ns_device_total_bytes{namespace='$namespace', instance='$host'}",
     "legendFormat": "total"
    },
    {
     "expr": "as_ns_device_used_bytes{namespace='$namespace', instance='$host'}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_ns_client_proxy_complete{namespace='$namespace', instance='$host'}",
     "legendFormat": "complete"
    },
    {
     "expr": "as_ns_client_proxy_error{namespace='$namespace', instance='$host'}",
     "legendFormat": "error"
    },
    {
     "expr": "as_ns_client_proxy_timeout{namespace='$namespace', instance='$host'}",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Operations Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "as_ns_client_read_success{namespace='$namespace', instance='$host'}",
     "legendFormat": "Read Success"
    },
    {
     "expr": "as_ns_client_write_success{namespace='$namespace', instance='$host'}",
     "legendFormat": "Write Success"
    },
    {
     "expr": "as_ns_client_delete_success{namespace='$namespace', instance='$host'}",
     "legendFormat": "Delete Success"
    }
   ]
  },
  {
   "title": "Operations Read Error/Notfound/Timeout",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_ns_client_read_error{namespace='$namespace', instance='$host'}",
     "legendFormat": "Read Error"
    },
    {
     "expr": "as_ns_client_read_not_found{namespace='$namespace', instance='$host'}",
     "legendFormat": "Read Notfound"
    },
    {
     "expr": "as_ns_client_read_timeout{namespace='$namespace', instance='$host'}",
     "legendFormat": "Read Timeout"
    }
   ]
  },
  {
   "title": "Operations Write Error/Dup/Timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_ns_client_write_error{namespace='$namespace', instance='$host'}",
     "legendFormat": "Write Error"
    },
    {
     "expr": "as_ns_retransmit_client_write_dup_res{namespace='$namespace', instance='$host'}",
     "legendFormat": "Write Dup Res"
    },
    {
     "expr": "as_ns_client_write_timeout{namespace='$namespace', instance='$host'}",
     "legendFormat": "Write Timeout"
    }
   ]
  },
  {
   "title": "Delete",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_ns_client_delete_success{namespace='$namespace', instance='$host'}",
     "legendFormat": "success"
    },
    {
     "expr": "as_ns_client_delete_not_found{namespace='$namespace', instance='$host'}",
     "legendFormat": "not-found"
    },
    {
     "expr": "as_ns_client_delete_error{namespace='$namespace', instance='$host'}",
     "legendFormat": "error"
    },
    {
     "expr": "as_ns_client_delete_timeout{namespace='$namespace', instance='$host'}",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Lookup Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_ns_query_lookups{namespace='$namespace', instance='$host'}",
     "legendFormat": "total"
    },
    {
     "expr": "as_ns_query_lookup_success{namespace='$namespace', instance='$host'}",
     "legendFormat": "success"
    },
    {
     "expr": "as_ns_query_lookup_error{namespace='$namespace', instance='$host'}",
     "legendFormat": "error"
    },
    {
     "expr": "as_ns_query_lookup_abort{namespace='$namespace', instance='$host'}",
     "legendFormat": "abort"
    }
   ]
  },
  {
   "title": "Aggregation Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_ns_query_agg{namespace='$namespace', instance='$host'}",
     "legendFormat": "total"
    },
    {
     "expr": "as_ns_query_agg_success{namespace='$namespace', instance='$host'}",
     "legendFormat": "success"
    },
    {
     "expr": "as_ns_query_agg_error{namespace='$namespace', instance='$host'}",
     "legendFormat": "error"
    },
    {
     "expr": "as_ns_query_agg_abort{namespace='$namespace', instance='$host'}",
     "legendFormat": "abort"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of Connections to Aerospike Node",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_cient_connections{instance='$host'}",
     "legendFormat": "client"
    },
    {
     "expr": "as_stats_fabric_connections{instance='$host'}",
     "legendFormat": "fabric"
    },
    {
     "expr": "as_stats_heartbeat_connections{instance='$host'}",
     "legendFormat": "heartbeat"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_batch_queue{instance='$host'}",
     "legendFormat": "batch"
    },
    {
     "expr": "as_stats_delete_queue{instance='$host'}",
     "legendFormat": "delete"
    },
    {
     "expr": "as_stats_tsvc_queue{instance='$host'}",
     "legendFormat": "tsvc"
    },
    {
     "expr": "as_stats_info_queue{instance='$host'}",
     "legendFormat": "info"
    },
    {
     "expr": "as_stats_tree_gc_queue{instance='$host'}",
     "legendFormat": "tree_gc"
    }
   ]
  },
  {
   "title": "Heartbeat Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_heartbeat_received_self{instance='$host'}",
     "legendFormat": "self"
    },
    {
     "expr": "as_stats_heartbeat_received_foreign{instance='$host'}",
     "legendFormat": "other"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "as_stats_heap_active_kbytes{instance='$host'}",
     "legendFormat": "active"
    },
    {
     "expr": "as_stats_heap_mapped_kbytes{instance='$host'}",
     "legendFormat": "mapped"
    },
    {
     "expr": "as_stats_heap_allocated_kbytes{instance='$host'}",
     "legendFormat": "allocated"
    }
   ]
  },
  {
   "title": "Heap Efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "as_stats_heap_efficiency_pct{instance='$host'}",
     "legendFormat": "efficiency"
    }
   ]
  },
  {
   "title": "Heap Site",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_heap_site_count{instance='$host'}",
     "legendFormat": "site"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Batch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_batch_initiate{instance='$host'}",
     "legendFormat": "initiated"
    },
    {
     "expr": "as_stats_batch_error{instance='$host'}",
     "legendFormat": "error"
    },
    {
     "expr": "as_stats_batch_timeout{instance='$host'}",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Batch Index",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_batch_index_initiate{instance='$host'}",
     "legendFormat": "initiated"
    },
    {
     "expr": "as_stats_batch_index_complete{instance='$host'}",
     "legendFormat": "completed"
    },
    {
     "expr": "as_stats_batch_index_error{instance='$host'}",
     "legendFormat": "error"
    },
    {
     "expr": "as_stats_batch_index_timeout{instance='$host'}",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Batch Index Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_batch_index_created_buffers{instance='$host'}",
     "legendFormat": "created"
    },
    {
     "expr": "as_stats_batch_index_destroyed_buffers{instance='$host'}",
     "legendFormat": "destroyed"
    },
    {
     "expr": "as_stats_batch_index_unused_buffers{instance='$host'}",
     "legendFormat": "unused"
    },
    {
     "expr": "as_stats_batch_index_huge_buffers{instance='$host'}",
     "legendFormat": "huge"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Fabric Control Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_fabric_ctrl_send_rate{instance='$host'}",
     "legendFormat": "send"
    },
    {
     "expr": "as_stats_fabric_ctrl_recv_rate{instance='$host'}",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Fabric Bulk Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_fabric_bulk_send_rate{instance='$host'}",
     "legendFormat": "send"
    },
    {
     "expr": "as_stats_fabric_bulk_recv_rate{instance='$host'}",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Fabric Bulk Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_fabric_meta_send_rate{instance='$host'}",
     "legendFormat": "send"
    },
    {
     "expr": "as_stats_fabric_meta_recv_rate{instance='$host'}",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Fabric Bulk Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_fabric_rw_send_rate{instance='$host'}",
     "legendFormat": "send"
    },
    {
     "expr": "as_stats_fabric_rw_recv_rate{instance='$host'}",
     "legendFormat": "recv"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "S_Index GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_sindex_gc_garbage_cleaned{instance='$host'}",
     "legendFormat": "cleaned"
    },
    {
     "expr": "as_stats_sindex_gc_garbage_found{instance='$host'}",
     "legendFormat": "found"
    },
    {
     "expr": "as_stats_sindex_gc_objects_validated{instance='$host'}",
     "legendFormat": "validated"
    }
   ]
  },
  {
   "title": "S_Index GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "as_stats_sindex_gc_list_creation_time{instance='$host'}",
     "legendFormat": "creation time"
    },
    {
     "expr": "as_stats_sindex_gc_list_deletion_time{instance='$host'}",
     "legendFormat": "deletion time"
    }
   ]
  }
 ]
}