{
 "title": "AWS ELB Classic Load Balancer",
 "description": "Visualize AWS ELB Classic Load Balancer metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": "dimension_values($region,AWS/ELB,Latency,LoadBalancerName)"
   }
  ]
 },
 "panels": [
  {
   "title": "RequestCount / Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Latency",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HTTPCode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Backend_4XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Backend_3XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Backend_2XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_4XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "SpilloverCount / SurgeQueueLength",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SpilloverCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SurgeQueueLength",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "HostCount / BackendConnectionErrors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}