{
 "title": "AWS ES",
 "description": "AWS Elastic Search",
 "tags": [ "CloudWatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "DomainName",
    "label": "Domain Name",
    "query": "dimension_values($region,AWS/ES,CPUUtilization,DomainName)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "dimension_values($region,AWS/ES,CPUUtilization,ClientId)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "MasterCPUUtilization",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "MasterJVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "AWS ES Cluster Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "SampleCount" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "SampleCount" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "Storage Free/Used space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClusterUsedSpace",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Document Search/Deleted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DeletedDocuments",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadLatency",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteLatency",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Nodes",
     "namespace": "AWS/ES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}