{
 "title": "CPU & Memory Utilisation Details by Group",
 "description": "This is experimental dashboard monitoring which provides CPU utilisation details for multi-core systems.  It allows to easily see if overall CPU usage is high or if there are overloaded cores.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(node_boot_time_seconds{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$job Percentage of CPU used",
   "type": "graph",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Percentage of CPU used {{instance}}"
    }
   ]
  },
  {
   "title": "$job CPU Busy System",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System, {{instance}}"
    }
   ]
  },
  {
   "title": "$job Memory Utilisation",
   "type": "graph",
   "description": "Basic Memory info",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemFree_bytes{job=~\"$job\"} - (node_memory_Cached_bytes{job=~\"$job\"} + node_memory_Buffers_bytes{job=~\"$job\"})",
     "legendFormat": "Memory Utilisation {{instance}}"
    }
   ]
  }
 ]
}