{
 "title": "Prometheus AlertManager",
 "description": "The dashborad using Prometheus AlertManager datasource 0.0.6 version.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "HostCPUUtilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"HostCPUUtilisation\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memory Usage Above 90%",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"Memory_Usage_Above_90_Percent\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "LoadAverage15m",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"LoadAverage15m\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Disk Will Fill In 4 Hours",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"DiskWillFillIn4Hours\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "WebsiteDown",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"EndpointDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SSLCertExpiringSoon",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"SSLCertExpiringSoon\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)", "labelSelector": "*", "target": "Query", "type": "timeserie" }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "labelSelector": "*", "legendFormat": "{{ summary }}", "target": "Query", "type": "table" },
    { "labelSelector": "*", "legendFormat": "{{ instance }}", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "All Alerts in 24 Hours",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sort_desc(sum(sum_over_time(ALERTS{alertstate=`firing`}[24h])) by (alertname))",
     "labelSelector": "*",
     "legendFormat": "{{ summary }}",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}