{
 "title": "Zookeeper Cluster Overview",
 "tags": [ "zookeeper" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(zk_ok,job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(zk_ok{job=\"$job\"}, instance)"
   },
   {
    "name": "zk_instance",
    "label": "zk_instance",
    "query": "label_values(zk_ok{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "zk_ok",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "expr": "count(zk_ok)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_ok}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "znode_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "zk_followers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "expr": "sum by(zk_instance) (zk_followers)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_instance}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "znode_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZNode Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "expr": "sum by(zk_instance) (zk_znode_count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_instance}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "znode_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "zk_outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(zk_instance) (zk_outstanding_requests)",
     "legendFormat": "{{zk_instance}}"
    }
   ]
  },
  {
   "title": "zk_approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(zk_instance) (zk_approximate_data_size)",
     "legendFormat": "{{zk_instance}}"
    }
   ]
  },
  {
   "title": "zk_num_alive_connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(zk_instance) (zk_num_alive_connections)",
     "legendFormat": "{{zk_instance}}"
    }
   ]
  },
  {
   "title": "zk_max_latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(zk_instance) (zk_max_latency)",
     "legendFormat": "{{zk_instance}}"
    }
   ]
  },
  {
   "title": "Packets_Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sent",
     "expr": "sum by(zk_instance) (zk_packets_sent)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_instance}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packets_Recieved",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sent",
     "expr": "sum by(zk_instance) (zk_packets_received)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_instance}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "File descriptor count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max",
     "expr": "sum by(zk_instance) (zk_max_file_descriptor_count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_instance}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "max_file_descriptor_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "zk_ephemerals_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "expr": "sum by(zk_instance) (zk_ephemerals_count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_instance}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "znode_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "expr": "sum by(zk_instance) (zk_watch_count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{zk_instance}}",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "watch_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "zk_avg_latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(zk_instance) (zk_avg_latency)",
     "legendFormat": "{{zk_avg_latency}}"
    }
   ]
  }
 ]
}